ALTER TABLE `faccliltemporales` ADD `Fecha` DATETIME NULL DEFAULT NULL AFTER `idUsuario`;
ALTER TABLE `faccliltemporales` CHANGE `numfaccli` `Numfaccli` INT(11) NULL DEFAULT NULL;
ALTER TABLE `faccliltemporales` CHANGE `idClientes` `idCliente` INT(11) NULL DEFAULT NULL;
ALTER TABLE `faccliltemporales` DROP `estadoFacCli`;
ALTER TABLE `faccliltemporales` DROP `FacCobros`;
ALTER TABLE `faccliltemporales` CHANGE `fechaFinal` `fechaVencimiento` DATETIME NULL DEFAULT NULL;
ALTER TABLE `facclit` DROP `formaPago`;
UPDATE `tiposVencimiento` SET `dias` = '0' WHERE `tiposVencimiento`.`id` = 1;
ALTER TABLE `albcliltemporales` CHANGE `idClientes` `idCliente` INT(11) NULL DEFAULT NULL; 
ALTER TABLE `albcliltemporales` CHANGE `fechaFinal` `Fecha` DATETIME NULL DEFAULT NULL;
ALTER TABLE `albcliltemporales` DROP `estadoAlbCli`;
ALTER TABLE `albcliltemporales` CHANGE `numalbcli` `Numalbcli` INT(11) NULL DEFAULT NULL; 
ALTER TABLE `pedcliltemporales` CHANGE `idPedcli` `Numpedcli` INT(11) NULL DEFAULT NULL; 
ALTER TABLE `pedcliltemporales` CHANGE `fechaFinal` `Fecha` DATETIME NULL DEFAULT NULL; 
ALTER TABLE `pedcliltemporales` CHANGE `idClientes` `idCliente` INT(11) NULL DEFAULT NULL; 
ALTER TABLE `pedclit` CHANGE `FechaPedido` `Fecha` DATE NOT NULL; 
ALTER TABLE `pedcliltemporales` DROP `estadoPedCli`;
UPDATE `albclit` SET `estado`='Procesado' WHERE estado='facturado';
UPDATE `pedclit` SET `estado`='Procesado' WHERE estado='facturado';
UPDATE `facclit` SET `estado`='Procesado' WHERE estado='facturado';
