ALTER TABLE `articulosTiendas` DROP PRIMARY KEY, ADD INDEX `idTienda_idArticulo` (`idArticulo`, `idTienda`) USING BTREE;
ALTER TABLE `articulosTiendas` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);
ALTER TABLE `ticketstemporales` CHANGE `fechaFinal` `fechaFinal` DATETIME NULL;
ALTER TABLE `ticketstemporales` DROP `total_ivas`;
ALTER TABLE `albprot` CHANGE `Su_numero` `Su_numero` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL;
ALTER TABLE `albprot` CHANGE `Fecha` `Fecha` DATETIME NOT NULL;
ALTER TABLE `albprot` CHANGE `Numalbpro` `Numalbpro` INT(11) NULL;
ALTER TABLE `albprot` CHANGE `idTienda` `idTienda` INT(11) NOT NULL;
ALTER TABLE `albprot` CHANGE `idUsuario` `idUsuario` INT(11) NOT NULL;
ALTER TABLE `albprot` CHANGE `idProveedor` `idProveedor` INT(11) NOT NULL;
ALTER TABLE `facprot` CHANGE `Numfacpro` `Numfacpro` INT(11) NULL;
ALTER TABLE `facprot` CHANGE `Su_num_factura` `Su_num_factura` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL;
ALTER TABLE `facprot` CHANGE `Fecha` `Fecha` DATETIME NOT NULL;
ALTER TABLE `facprot` CHANGE `idTienda` `idTienda` INT(11) NOT NULL;
ALTER TABLE `facprot` CHANGE `idUsuario` `idUsuario` INT(11) NOT NULL;
ALTER TABLE `facprot` CHANGE `idProveedor` `idProveedor` INT(11) NOT NULL;
ALTER TABLE `albclit` CHANGE `Numalbcli` `Numalbcli` INT(11) NULL;
ALTER TABLE `albclit` CHANGE `Fecha` `Fecha` DATETIME NOT NULL;
ALTER TABLE `albclit` CHANGE `idTienda` `idTienda` INT(11) NOT NULL;
ALTER TABLE `albclit` CHANGE `idUsuario` `idUsuario` INT(11) NOT NULL;
ALTER TABLE `albclit` CHANGE `idCliente` `idCliente` INT(11) NOT NULL;
ALTER TABLE `facclit` CHANGE `Numfaccli` `Numfaccli` INT(11) NULL;
ALTER TABLE `facclit` CHANGE `Fecha` `Fecha` DATETIME NOT NULL;
ALTER TABLE `facclit` CHANGE `idTienda` `idTienda` INT(11) NOT NULL;
ALTER TABLE `facclit` CHANGE `idUsuario` `idUsuario` INT(11) NOT NULL;
ALTER TABLE `facclit` CHANGE `idCliente` `idCliente` INT(11) NOT NULL;
ALTER TABLE `articulos` CHANGE `fecha_modificado` `fecha_modificado` DATETIME NULL;
ALTER TABLE `articulos` CHANGE `articulo_name` `articulo_name` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL; 
