ALTER TABLE modulo_balanza
RENAME COLUMN conTecla to conSeccion,
ADD COLUMN Grupo TINYINT UNSIGNED NOT NULL,
ADD COLUMN Dirección TINYINT UNSIGNED NOT NULL,
ADD COLUMN IP VARCHAR(45) NOT NULL,
ADD COLUMN soloPLUS BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE modulo_balanza_plus
RENAME COLUMN tecla to seccion,